# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TP_Tuner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'CodableFirebase'

  # Pods for TP_Tuner

end
